<a href="https://colab.research.google.com/github/robert-shepherd/fpl/blob/main/Project_3_1_model_build_setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Model build setup


---

The purpose of this script is to select features to be used in the model, partition the data into a train/test split, and separate data into X (feature variables) and Y (response variable)

Data sources:
* Data post feature engineering:  https://raw.githubusercontent.com/robert-shepherd/fpl/main/fpl_features.csv

Output:

* Data is downloaded and subsequently saved to:
 * https://raw.githubusercontent.com/robert-shepherd/fpl/main/X_train.csv
 * https://raw.githubusercontent.com/robert-shepherd/fpl/main/X_test.csv
 * https://raw.githubusercontent.com/robert-shepherd/fpl/main/Y_train.csv
 * https://raw.githubusercontent.com/robert-shepherd/fpl/main/Y_test.csv

In [ ]:
# Loading libraries
import pandas as pd
import pickle
import numpy as np
import scipy.stats as stats
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# Import measures
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_squared_error

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

## Setup

In [ ]:
# Read in data
url = 'https://raw.githubusercontent.com/robert-shepherd/fpl/main/fpl_features.csv'

df = pd.read_csv(url)

In [ ]:
# Check data
df.head(10)

   element  fixture  ...  transfers_out_ratio_lag  transfers_out_ratio_rolling
0        1        1  ...                      NaN                          NaN
1        1       14  ...                 0.000000                          NaN
2        1       21  ...                 0.065206                          NaN
3        1       33  ...                 0.102609                          NaN
4        1       46  ...                 0.078905                          NaN
5        1       51  ...                 0.098402                     0.069024
6        1       61  ...                 0.059221                     0.080869
7        1       74  ...                 0.030261                     0.073880
8        1       81  ...                 0.276466                     0.108651
9        1       93  ...                 0.180439                     0.128958

[10 rows x 98 columns]

In [ ]:
# Select only features to be used to create the model
variables_for_selection = ['total_points','was_home','position',
'opponent_strength',
'points_lag_1','points_lag_2','points_lag_3','points_lag_4',
'points_lag_5',
'points_lag_6','points_lag_7','points_lag_8',
'points_lag_9','points_lag_10',
'minutes_lag',
'minutes_rolling', 'goals_scored_lag', 'goals_scored_rolling',
'assists_lag', 'assists_rolling', 'clean_sheets_lag',
'clean_sheets_rolling', 'goals_conceded_lag', 'goals_conceded_rolling',
'saves_lag', 'saves_rolling', 'cards_lag', 'cards_rolling', 'bonus_lag',
'bonus_rolling', 'bps_lag', 'bps_rolling', 'influence_lag',
'influence_rolling', 'creativity_lag', 'creativity_rolling',
'threat_lag', 'threat_rolling', 'selected_lag', 'selected_rolling',
'transfers_in_ratio_lag', 'transfers_in_ratio_rolling',
'transfers_out_ratio_lag', 'transfers_out_ratio_rolling']

df = df[variables_for_selection]
df.head()

   total_points  was_home  ... transfers_out_ratio_lag  transfers_out_ratio_rolling
0             3      True  ...                     NaN                          NaN
1             3     False  ...                0.000000                          NaN
2             3      True  ...                0.065206                          NaN
3             1     False  ...                0.102609                          NaN
4             2     False  ...                0.078905                          NaN

[5 rows x 44 columns]

In [ ]:
# Using one hot encoding to encode categorical variables
df_encoded = pd.get_dummies(data=df, columns=['was_home','position'],
                            drop_first=True)
df_encoded.head()

   total_points  opponent_strength  ...  position_GKP  position_MID
0             3                  5  ...             1             0
1             3                  4  ...             1             0
2             3                  3  ...             1             0
3             1                  2  ...             1             0
4             2                  3  ...             1             0

[5 rows x 46 columns]

In [ ]:
# Splitting the model dataset so Y is the target variable (total points) and 
# X are the predictors
X = df_encoded.drop(['total_points'], axis=1)
Y = df_encoded['total_points']

In [ ]:
# Splitting between training and test set
test_size = 0.20
seed = 42
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size
                                                    , random_state=seed)

print('X_train      : ',X_train.shape)
print('X_test       : ',X_test.shape)
print('Y_train      : ',Y_train.shape)
print('Y_test       : ',Y_test.shape)

X_train      :  (40388, 45)
X_test       :  (10098, 45)
Y_train      :  (40388,)
Y_test       :  (10098,)

In [ ]:
# Writing out files so that it is consistent between runs
X_train.to_csv('X_train.csv',index=False) 
files.download('X_train.csv')

X_test.to_csv('X_test.csv',index=False) 
files.download('X_test.csv')

Y_train.to_csv('Y_train.csv',index=False) 
files.download('Y_train.csv')

Y_test.to_csv('Y_test.csv',index=False) 
files.download('Y_test.csv')

File downloaded to local machine and uploaded to GitHub